.\"                                      Hey, EMACS: -*- nroff -*-
.TH OPENYAHTZEE 6 "January  6, 2007"
.SH NAME
openyahtzee \- play a classic game of Yahtzee
.SH SYNOPSIS
.B openyahtzee
.SH DESCRIPTION
\fBopenyahtzee\fP lets you play a game of Yahtzee.
.SH OPTIONS
This program does not accept any options at the moment.
.SH AUTHOR
openyahtzee was written by Guy Rutenberg <guyrutenberg@gmail.com>
.PP
This manual page was written by Zak B. Elep <zakame@spunge.org>,
for the Debian project (but may be used by others).

