// $Header$
/***************************************************************************
 *   Copyright (C) 2006 by Guy Rutenberg   *
 *   guy@Guy_Computer   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// -*- C++ -*- generated by wxGlade 0.4 on Wed Oct 11 10:39:57 2006
//this file was originally base on the output of wxGlades but i had to make many changes - Guy

#include "SettingsDialog.h"
#include "MainFrame.h"


SettingsDialog::SettingsDialog(wxWindow* parent, int id):
    wxDialog(parent, wxID_ANY, wxT("Settins Dialog"), wxDefaultPosition, wxDefaultSize, wxCLOSE_BOX | wxCAPTION)
{
    // begin wxGlade: SettingsDialog::SettingsDialog
    label_1 = new wxStaticText(this, -1, wxT("High-score table size:"));
    spin_ctrl = new wxSpinCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS,0,1024,20);
    button_3 = new wxToggleButton(this, ID_RESETHIGHSCORE, wxT("reset high-score table"));
    button_1 = new wxButton(this, wxID_OK);
    button_2 = new wxButton(this, wxID_CANCEL);

    set_properties();
    do_layout();
    // end wxGlade
}

BEGIN_EVENT_TABLE( SettingsDialog, wxDialog)
	EVT_TOGGLEBUTTON(ID_RESETHIGHSCORE, SettingsDialog::OnResetHighScore)
END_EVENT_TABLE();

void SettingsDialog::set_properties()
{
    // begin wxGlade: SettingsDialog::set_properties
    //SetTitle(wxT("Settings Dialog")); /*unneeded anymore -guy*/
    //button_1->SetDefault();/*unneeded anymore -guy*/
    // end wxGlade
}


void SettingsDialog::do_layout()
{
    // begin wxGlade: SettingsDialog::do_layout
    wxBoxSizer* top_sizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* highscoresizer = new wxBoxSizer(wxHORIZONTAL);
    highscoresizer->Add(label_1, 0, wxALL|wxADJUST_MINSIZE, 10);
    highscoresizer->Add(spin_ctrl, 0, wxALL|wxADJUST_MINSIZE, 10);
    top_sizer->Add(highscoresizer, 0, 0, 0);
    top_sizer->Add(button_3, 0,wxALL|wxALIGN_RIGHT|wxADJUST_MINSIZE, 10);
    sizer_2->Add(button_1, 0, wxALL|wxADJUST_MINSIZE, 10);
    sizer_2->Add(button_2, 0, wxALL|wxADJUST_MINSIZE, 10);
    top_sizer->Add(sizer_2, 1, 0, 0);
    SetAutoLayout(true);
    SetSizer(top_sizer);
    top_sizer->Fit(this);
    top_sizer->SetSizeHints(this);
    Layout();
    // end wxGlade
}


void SettingsDialog::OnResetHighScore(wxCommandEvent& event)
{
	if(!button_3->GetValue()){
		button_3->SetValue(0);
		return;
	}
	
	int answer = wxMessageBox(wxT("Are you sure you want to reset the high-score table? After reseting the high score table, you won't be able to restore it!\nThe new high-score table size will be as specified in this dialog."),wxT("High-score table reset"),wxYES_NO|wxICON_EXCLAMATION);

	if(answer==wxNO)
		button_3->SetValue(0);
}

void SettingsDialog::SetData(SettingsDialogData data)
{
	spin_ctrl->SetValue(data.highscoresize);
}

SettingsDialogData SettingsDialog::GetData()
{
	SettingsDialogData data;
	data.highscoresize = spin_ctrl->GetValue();
	data.reset = button_3->GetValue();
	return data;
}