// $Header: $
/***************************************************************************
 *   Copyright (C) 2006 by Guy Rutenberg   *
 *   guyrutenberg@gmail.com   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
// -*- C++ -*- generated by wxGlade 0.4.1cvs on Tue Feb 27 17:58:29 2007 from /home/guy/about.wgt

#include <wx/wx.h>
#include <wx/image.h>
#include "wxDynamicBitmap.h"

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef ABOUT_H
#define ABOUT_H


class AboutDialog: public wxDialog {
public:
    // begin wxGlade: AboutDialog::ids
    // end wxGlade

    AboutDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: AboutDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AboutDialog::attributes
    wxDynamicBitmap* bitmap_1;
    wxStaticText* app_label;
    wxStaticText* label_desc;
    wxStaticText* label_copyright;
    wxStaticText* label_1;
    wxPanel* notebook_main_pane_about;
    wxStaticText* label_7;
    wxScrolledWindow* notebook_main_pane_authors;
    wxStaticText* label_6;
    wxScrolledWindow* notebook_main_pane_thanks;
    wxStaticText* label_15;
    wxScrolledWindow* notebook_main_pane_license;
    wxNotebook* notebook_main;
    wxButton* close_button;
    // end wxGlade
}; // wxGlade: end class



#endif // ABOUT_H
