// $Header$
/***************************************************************************
 *   Copyright (C) 2006 by Guy Rutenberg   *
 *   guy@Guy_Computer   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// -*- C++ -*- generated by wxGlade 0.4 on Wed Oct 11 10:39:57 2006
//this file was originally base on the output of wxGlades but i had to make many changes - Guy

#include <wx/wx.h>
// begin wxGlade: ::dependencies
// end wxGlade
#include <wx/spinctrl.h>
#include <wx/tglbtn.h>
#include "ObjectsID.h"


#ifndef SETTINGSDIALOG_H
#define SETTINGSDIALOG_H

struct SettingsDialogData {
	int highscoresize;
	bool reset;
};

class SettingsDialog: public wxDialog {
public:
    // begin wxGlade: SettingsDialog::ids
    // end wxGlade

    SettingsDialog(wxWindow* parent, int id);
	
	SettingsDialogData GetData();
	void SetData(SettingsDialogData data);
	
	void OnResetHighScore(wxCommandEvent& event);
private:
    // begin wxGlade: SettingsDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade
	void ConnectEventTable();
	


protected:
    // begin wxGlade: SettingsDialog::attributes
    wxStaticText* label_1;
    wxSpinCtrl* spin_ctrl;
    wxToggleButton* button_3; //the reset button
    wxButton* button_1;
    wxButton* button_2;

	DECLARE_EVENT_TABLE();
    // end wxGlade
	
}; // wxGlade: end class


#endif // SETTINGSDIALOG_H
